TrajectoryPlannerROS:

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  sim_time: 1.5
  pdist_scale: 1
  gdist_scale: 2.5
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 0.2
  max_vel_theta: 0.5
  meter_scoring: true
  heading_lookahead: 0.4
